name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push-cli-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/cli
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: deploy/docker/Dockerfile.cli
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  release-helm-chart:
    runs-on: ubuntu-latest
    needs: build-and-push-cli-image
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1
      - name: Update chart appVersion and release
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          TAG=${GITHUB_REF#refs/tags/}
          sed -i "s/^appVersion: .*/appVersion: ${TAG}/" charts/pypgflow/Chart.yaml
          git add charts/pypgflow/Chart.yaml
          git commit -m "Update Chart.yaml appVersion to ${TAG} [skip ci]"
          git push
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
